name: CI for Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTHONIOENCODING: "UTF-8"
  PYTHON_VERSIONS: ""

jobs:
  test-template:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Copier
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        python -m pip install copier
    - name: Generate test project, install deps, format, and test
      run: |
        copier --vcs-ref HEAD --defaults --data "minimal_python_version=${{ matrix.python-version }}" copy ./ ../test/test-project
        cd ../test/test-project
        make install
        make format
        make check-all
